services:
  - type: web
    name: youtube-downloader-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn you:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
    plan: free 